[project]
name = "humanleague"
version = "2.4.5"
authors = [
  { name="Andrew Smith", email="andrew@friarswood.net" },
]
license = "MIT"
license-files = ["LICENCE", "LICENSE.md"]
description = "Microsynthesis using quasirandom sampling and/or IPF"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=2.4.5",
    "pandas>=3.0.3",
]

[build-system]
requires = ["scikit-build-core >=0.12", "nanobind >=2.12.0"]
build-backend = "scikit_build_core.build"

[dependency-groups]
dev = [
  "pytest>=9.0.3",
  "ruff>=0.15.17",
  "build>=1.5.0",
  "ty>=0.0.49",
  "pre-commit>=4.6.0",
  "pandas-stubs>=3.0.3.260530",
]

[tool.pytest.ini_options]
testpaths = [
  "tests"
]

[tool.scikit-build]
# Protect the configuration against future changes in scikit-build-core
minimum-version = "build-system.requires"

# Setuptools-style build caching in a local directory
build-dir = "build/{wheel_tag}"

# Build stable ABI wheels for CPython 3.12+
wheel.py-api = "cp312"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ARG", "B", "C", "D103", "E", "F", "I", "N", "PERF", "PTH", "RET", "RUF", "SIM", "UP", "W"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401", "F403"]
"tests/*.py" = ["D103", "N802"]
