
name: Code coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.13" ]
    steps:
    - uses: actions/checkout@v6
    - name: "Setup uv ${{ matrix.python-version }} / ${{ matrix.os }}"
      uses: astral-sh/setup-uv@v8
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: |
        CXXFLAGS=-coverage uv sync --dev
    - name: Test
      run: |
        uv run pytest
    - name: Upload
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash) -Z
