name: PyPI release

on:
  push:
    branches:
    - main

jobs:
  bump-version:
    name: Bump package version
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: current_version
      run: echo "current_version=$(grep 'Version' DESCRIPTION | cut -d ' ' -f2)" >> $GITHUB_ENV
    - name: FragileTech/bump-version
      uses: FragileTech/bump-version@main
      with:
        current_version: "${{ env.current_version }}"
        files: DESCRIPTION
        commit_name: Version autobump
        commit_email: andrew@friarswood.net
        login: virgesmith
        token: "${{ secrets.REPO_PAT }}"
    - name: Create dist
      run: |
        pip install pybind11
        python setup.py sdist
    # - name: artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: dt_utils_${{ matrix.python-version }}
    #     path: |
    #       dist
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/

# on:
#   workflow_dispatch:
#   workflow_run:
#     workflows: [Python test]
#     types: [ completed ]
#     branches: [ main ]

# jobs:
#   package:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     steps:
#     - uses: actions/checkout@v3
#     - name: "pip: Python 3.11 / ubuntu-latest"
#       uses: actions/setup-python@v4
#       with:
#         python-version: "3.11"
#     - name: Bump version
#       run: |
#         python -m pip install bump2version pybind11
#         bump2version patch
#     - name: Create dist
#       run: |
#         python setup.py sdist
#     - name: artifacts
#       uses: actions/upload-artifact@v3
#       with:
#         name: dt_utils_${{ matrix.python-version }}
#         path: |
#           dist
#     - name: Publish
#       uses: pypa/gh-action-pypi-publish@release/v1
#       with:
#         password: ${{ secrets.TEST_PYPI_API_TOKEN }}
#         repository-url: https://test.pypi.org/legacy/
